version: '3.5'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydoop
      - MYSQL_USER=mydoop
      - MYSQL_PASSWORD=mydoop